baseURL: "https://arkalim.netlify.app"
languageCode: en-us
title: Nikhilesh Varma Penmesta
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: education
      name: Education
      url: /education
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Nikhilesh Varma Penmesta"
    subtitle: Hi There 👋  I’m Nikhilesh, a passionate Data Analyst with 3 years of experience in Data Engineering and Analytics. I specialize in designing and optimizing ETL pipelines, developing data models, and using tools like Python, SQL, Tableau, and AWS to transform complex data into actionable insights. My work has improved business processes, enhanced decision-making, and boosted system performance. I excel in collaborating with cross-functional teams, automating workflows, and applying machine learning models to drive business growth. Driven by a curiosity for technology, I’m committed to leveraging data to solve real-world problems and continuously explore innovative solutions.

 
    imageUrl: "home/nikhilesh-formal-photo.jpeg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:nikhileshvarmapenmesta@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nikhilesh-penmesta/"
    - name: "github"
      url: "https://github.com/857264999"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
